### ISSUE TITLE
no crypto in order

### ISSUE THREAD

**Issue by lengyijun** [IBM/BuildingABlockchainApplicationOutsideofComposer#4]
Sending build context to Docker daemon  2.048kB 
Step 1/3 : FROM docker.io/hyperledger/fabric-orderer:x86_64-1.1.0                               
 ---> ce0c810df36a                              
Step 2/3 : RUN mkdir /orderer                   
 ---> Using cache                               
 ---> 196372925b7c                              
Step 3/3 : COPY crypto /orderer/crypto          
lstat crypto: no such file or directory

**Comment by ljbennett62** [comment]
@lengyijun - which platform are you running this on? MAC?  I just ran it with no problems.  I am wondering if you have docker images laying around.  You want to run the following: 1) ` docker stop $(docker ps -aq)`  2) `docker rm $(docker ps -aq)` 3) `docker rmi -f $(docker images -q)`.  Then you can run the commands to clean up and then build the app.  This is what I am seeing 
![image](https://user-images.githubusercontent.com/17774650/42902735-78dac732-8a84-11e8-90f9-9f0d099e9e33.png)

**Comment by ljbennett62** [comment]
@lengyijun  - Since it is pulling from your cache - I think you need to clear your cache.

**Comment by guangyingyuan** [comment]
I think these configtxgen    cryptogen  tools is based on MAC, cant run linux version .
